# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0o-qBwZYh6S3xw6PTUVbRPJ73y7AiiL
"""



import sklearn
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = load_breast_cancer()
label_name = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']
print(label_name)
print('class label = ',labels[0])
print(feature_names)
print(features[0])
train, test, train_labels, test_labels = train_test_split(features,labels,test_size=0.33,random_state=42)
gnb = GaussianNB()
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)
print(preds)
print(accuracy_score(test_labels, preds))